services:
  web:
    restart: always
    build:
      context: ./webserver
      target: development
    container_name: "web_fortune"
    tty: true
    command: ["npm", "run", "dev"]
    environment:
    - API_ENDPOINT=http://api:8000/
    volumes:
      - ./webserver/app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 80:80
  api:
    restart: always
    build: ./apserver
    container_name: "api_fortune"
    working_dir: /opt/myapp
    command: ["python","manage.py","runserver","0.0.0.0:8000"]
    environment:
      DATABASE_NAME: myproject
      USER_NAME: pythonMySql1
      PASSWORD_NAME: pythonMySql1
      HOST_NAME: db
    volumes:
      - ./apserver/myapp:/opt/myapp
    tty: true
    ports:
      - 8000:8000
  db:
    image: mysql:8.0.37-oracle
    container_name: "db_fortune"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myproject
      MYSQL_USER: pythonMySql1
      MYSQL_PASSWORD: pythonMySql1
      TZ: 'Asia/Tokyo'
    command: mysqld
    volumes:
      - ./dbserver/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
